version: {build}

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          VCVARS_COMMANDLINE: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86'
          CMAKE_GENERATOR: Visual Studio 14 2015
          QT_DIR: C:\Qt\5.8\msvc2015
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          VCVARS_COMMANDLINE: '\'"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86'
          CMAKE_GENERATOR: Visual Studio 14 2015
          QT_DIR: C:\Qt\5.6\msvc2015

before_build:
    - call %VCVARS_COMMANDLINE%
    - set Path=%QT_DIR%;%Path%
    - cd tests
    - mkdir _build
    - cd _build
    - cmake -G "%CMAKE_GENERATOR%" ..

build:
    project: tests\_build\ALL_BUILD.vcxproj


test_script:
    - msbuild "%APPVEYOR_BUILD_FOLDER%\tests\_build\RUN_TESTS.vcxproj" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"