name: Check for Code Updates

on:
    push:
    schedule:
        - cron: '1 * 1 * *'
    workflow_dispatch:

jobs:
    check-http-status-codes-update:
        name: Check for HTTP Status Codes Update
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm install
            - uses: actions/github-script@v2
              with:
                script: |
                    const path = require( 'path' );
                    console.log( context );
                    require( path.resolve( './.github/checkForHttpStatusCodesUpdate.js' ) )( { github, core, context, dryRun: true } );
