name: Check for Code Updates

on:
    schedule:
        - cron: '1 * 1 * *'
    workflow_dispatch:

jobs:
    check-http-status-codes-update:
        name: Check for HTTP Status Codes Update
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/github-script@v2
              with:
                script: |
                    const path = require( 'path' );
                    const scriptPath = path.resolve( './.github/checkForHttpStatusCodesUpdate.js' );
                    await require( scriptPath )( { github, core } );